package windowing;
import static org.lwjgl.glfw.GLFW.*;

public enum HintConstant {
	OPENGL_API(GLFW_OPENGL_API),
	OPENGL_ES_API(GLFW_OPENGL_ES_API),
	NO_ROBUSTNESS(GLFW_NO_ROBUSTNESS),
	NO_RESET_NOTIFICATION(GLFW_NO_RESET_NOTIFICATION), 
	LOSE_CONTEXT_ON_RESET(GLFW_LOSE_CONTEXT_ON_RESET),
	ANY_RELEASE_BEHAVIOR(GLFW_ANY_RELEASE_BEHAVIOR), 
	RELEASE_BEHAVIOR_FLUSH(GLFW_RELEASE_BEHAVIOR_FLUSH), 
	RELEASE_BEHAVIOR_NONE(GLFW_RELEASE_BEHAVIOR_NONE),
	OPENGL_ANY_PROFILE(GLFW_OPENGL_ANY_PROFILE), 
	OPENGL_CORE_PROFILE(GLFW_OPENGL_CORE_PROFILE), 
	OPENGL_COMPAT_PROFILE(GLFW_OPENGL_COMPAT_PROFILE);
	
	public final int type;
	
	private HintConstant(int value){
		this.type = value;
	}
}
