package windowing;
import static org.lwjgl.glfw.GLFW.*;

public enum WindowHint{
	RESIZABLE(GLFW_RESIZABLE),
	VISIBLE(GLFW_VISIBLE),
	DECORATED(GLFW_DECORATED),
	AUTO_ICONIFY(GLFW_AUTO_ICONIFY),
	FLOATING(GLFW_FLOATING),
	RED_BITS(GLFW_RED_BITS),
	GREEN_BITS(GLFW_GREEN_BITS),
	BLUE_BITS(GLFW_BLUE_BITS),
	ALPHA_BITS(GLFW_ALPHA_BITS),
	DEPTH_BITS(GLFW_DEPTH_BITS),
	STENCIL_BITS(GLFW_STENCIL_BITS),
	ACCUM_RED_BITS(GLFW_ACCUM_RED_BITS),
	ACCUM_GREEN_BITS(GLFW_ACCUM_GREEN_BITS),
	ACCUM_BLUE_BITS(GLFW_ACCUM_BLUE_BITS),
	ACCUM_ALPHA_BITS(GLFW_ACCUM_ALPHA_BITS),
	AUX_BUFFERS(GLFW_AUX_BUFFERS),
	SAMPLES(GLFW_SAMPLES),
	REFRESH_RATE(GLFW_REFRESH_RATE),
	STEREO(GLFW_STEREO),
	SRGB_CAPABLE(GLFW_SRGB_CAPABLE),
	CLIENT_API(GLFW_CLIENT_API),
	CONTEXT_VERSION_MAJOR(GLFW_CONTEXT_VERSION_MAJOR),
	CONTEXT_VERSION_MINOR(GLFW_CONTEXT_VERSION_MINOR),
	CONTEXT_ROBUSTNESS(GLFW_CONTEXT_ROBUSTNESS),
	CONTEXT_RELEASE_BEHAVIOR(GLFW_CONTEXT_RELEASE_BEHAVIOR),
	OPENGL_FORWARD_COMPAT(GLFW_OPENGL_FORWARD_COMPAT),
	OPENGL_DEBUG_CONTEXT(GLFW_OPENGL_DEBUG_CONTEXT),
	OPENGL_PROFILE(GLFW_OPENGL_PROFILE);
	
	public final int type;
	
	private WindowHint(int type){
		this.type = type;
	}
}
