package shaders.introspection;
import static org.lwjgl.opengl.GL30.*;
import static org.lwjgl.opengl.GL42.*;
import static org.lwjgl.opengl.GL43.*;

public enum Interface {

	UNIFORM(GL_UNIFORM),
	UNIFORM_BLOCK(GL_UNIFORM_BLOCK),
	ATOMIC_COUNTER_BUFFER(GL_ATOMIC_COUNTER_BUFFER),
	PROGRAM_INPUT(GL_PROGRAM_INPUT),
	PROGRAM_OUTPUT(GL_PROGRAM_OUTPUT),
	VERTEX_SUBROUTINE(GL_VERTEX_SUBROUTINE),
	TESS_CONTROL_SUBROUTINE(GL_TESS_CONTROL_SUBROUTINE),
	TESS_EVALUATION_SUBROUTINE(GL_TESS_EVALUATION_SUBROUTINE),
	GEOMETRY_SUBROUTINE(GL_GEOMETRY_SUBROUTINE),
	FRAGMENT_SUBROUTINE(GL_FRAGMENT_SUBROUTINE),
	COMPUTE_SUBROUTINE(GL_COMPUTE_SUBROUTINE),
	VERTEX_SUBROUTINE_UNIFORM(GL_VERTEX_SUBROUTINE_UNIFORM),
	TESS_CONTROL_SUBROUTINE_UNIFORM(GL_TESS_CONTROL_SUBROUTINE_UNIFORM),
	TESS_EVALUATION_SUBROUTINE_UNIFORM(GL_TESS_EVALUATION_SUBROUTINE_UNIFORM),
	GEOMETRY_SUBROUTINE_UNIFORM(GL_GEOMETRY_SUBROUTINE_UNIFORM),
	FRAGMENT_SUBROUTINE_UNIFORM(GL_FRAGMENT_SUBROUTINE_UNIFORM),
	COMPUTE_SUBROUTINE_UNIFORM(GL_COMPUTE_SUBROUTINE_UNIFORM),
	TRANSFORM_FEEDBACK_VARYING(GL_TRANSFORM_FEEDBACK_VARYING),
	TRANSFORM_FEEDBACK_BUFFER(GL_TRANSFORM_FEEDBACK_BUFFER),
	BUFFER_VARIABLE(GL_BUFFER_VARIABLE),
	SHADER_STORAGE_BLOCK(GL_SHADER_STORAGE_BLOCK);
	
	public final int value;
	
	private Interface(int type){
		value = type;
	}
}
