package textures.enums;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.opengl.GL12.*;
import static org.lwjgl.opengl.GL13.*;
import static org.lwjgl.opengl.GL14.*;
import static org.lwjgl.opengl.GL30.*;
import static org.lwjgl.opengl.GL44.*;

public enum TexParamEnum {
	CLAMP_TO_EDGE(GL_CLAMP_TO_EDGE),
	REPEAT(GL_REPEAT),
	CLAMP_TO_BORDER(GL_CLAMP_TO_BORDER),
	MIRRORED_REPEAT(GL_MIRRORED_REPEAT),
	MIRROR_CLAMP_TO_EDGE(GL_MIRROR_CLAMP_TO_EDGE),
	RED(GL_RED),
	GREEN(GL_GREEN),
	BLUE(GL_BLUE),
	ALPHA(GL_ALPHA),
	ZERO(GL_ZERO),
	ONE(GL_ONE),
	NEAREST(GL_NEAREST),
	LINEAR(GL_LINEAR),
	NEAREST_MIPMAP_NEAREST(GL_NEAREST_MIPMAP_NEAREST),
	NEAREST_MIPMAP_LINEAR(GL_NEAREST_MIPMAP_LINEAR),
	LINEAR_MIPMAP_NEAREST(GL_LINEAR_MIPMAP_NEAREST),
	LINEAR_MIPMAP_LINEAR(GL_LINEAR_MIPMAP_LINEAR),
	LEQUAL(GL_LEQUAL),
	GEQUAL(GL_GEQUAL),
	LESS(GL_LESS),
	GREATER(GL_GREATER),
	EQUAL(GL_EQUAL),
	NOTEQUAL(GL_NOTEQUAL),
	ALWAYS(GL_ALWAYS),
	NEVER(GL_NEVER),
	NONE(GL_NONE),
	COMPARE_REF_TO_TEXTURE(GL_COMPARE_REF_TO_TEXTURE),
	DEPTH_COMPONENT(GL_DEPTH_COMPONENT),
	STENCIL_INDEX(GL_STENCIL_INDEX);
	
	public final int value;
	
	private TexParamEnum(int type){
		value = type;
	}

}
