package textures.enums;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.opengl.GL12.*;
import static org.lwjgl.opengl.GL14.*;
import static org.lwjgl.opengl.GL33.*;
import static org.lwjgl.opengl.GL43.*;

public enum TexParam {

	DEPTH_STENCIL_MODE(GL_DEPTH_STENCIL_TEXTURE_MODE),
	BASE_LEVEL(GL_TEXTURE_BASE_LEVEL),
	BORDER_COLOR(GL_TEXTURE_BORDER_COLOR),
	COMPARE_MODE(GL_TEXTURE_COMPARE_MODE),
	COMPARE_FUNC(GL_TEXTURE_COMPARE_FUNC),
	LOD_BIAS(GL_TEXTURE_LOD_BIAS),
	MAG_FILTER(GL_TEXTURE_MAG_FILTER),
	MAX_LEVEL(GL_TEXTURE_MAX_LEVEL),
	MAX_LOD(GL_TEXTURE_MAX_LOD),
	MIN_FILTER(GL_TEXTURE_MIN_FILTER),
	MIN_LOD(GL_TEXTURE_MIN_LOD),
	SWIZZLE_R(GL_TEXTURE_SWIZZLE_R),
	SWIZZLE_G(GL_TEXTURE_SWIZZLE_G),
	SWIZZLE_B(GL_TEXTURE_SWIZZLE_B),
	SWIZZLE_A(GL_TEXTURE_SWIZZLE_A),
	SWIZZLE_RGBA(GL_TEXTURE_SWIZZLE_RGBA),
	WRAP_S(GL_TEXTURE_WRAP_S),
	WRAP_T(GL_TEXTURE_WRAP_T),
	WRAP_R(GL_TEXTURE_WRAP_R);

	public final int value;
	
	private TexParam(int type){
		value = type;
	}
}
